# Generated by Django 3.2.21 on 2024-02-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
