# Generated by Django 3.2.21 on 2024-02-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_categoria_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='image',
        ),
    ]
