# Generated by Django 3.2.23 on 2024-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20231217_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='short_desc',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
